name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Install libvips
      run: sudo apt-get update -qq && sudo apt-get install --fix-missing -y libvips
    - name: Build with Jekyll
      run: |
        bundle exec jekyll build
    - name: Configure Pages
      if: github.event_name == 'push'
      uses: actions/configure-pages@v5
    - name: Upload Pages artifact
      if: github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
    - name: Deploy to GitHub Pages
      if: github.event_name == 'push'
      uses: actions/deploy-pages@v4
